name: sound_simulation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - h5py
  - matplotlib
  - numpy
  - scipy
  - tqdm
  - pyvista
  - fastapi
  - uvicorn
  - python-socketio

